version: '3.8'

services:
  server:
    build: .
    container_name: node_server
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
